project:
  render:
    - tutorial.qmd
title: 'Tutorial 1 Solutions: Core Skills of a Business Scientist in the GenAI Era'
format:
  html:
    output-file: "tutorial-r-solutions"
    output-ext:  "html"
