project:
  render:
    - tutorial.qmd
title: 'Tutorial 1 Teaching Guide: Core Skills of a Business Scientist in the GenAI Era'
format:
  html:
    output-file: "tutorial-r-teaching-guide"
    output-ext:  "html"
